# Generated by Django 5.1.5 on 2025-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('price', models.IntegerField(verbose_name='Цена за блюдо')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('total_price', models.IntegerField(verbose_name='Финальная стоимость')),
                ('items', models.JSONField(verbose_name='Все блюда')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Готово', 'Готово'), ('Оплачено', 'Оплачено')], default='В ожидании', max_length=20)),
            ],
        ),
    ]
